name: flutter_soloud_example
description: Demonstrates how to use the flutter_soloud plugin.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
homepage: https://github.com/alnitak/flutter_soloud
maintainer: Marco Bavagnoli (@lildeimos)

version: 0.1.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  audio_session: ^0.2.2

  cupertino_icons: ^1.0.8
  
  file_picker: ^10.3.2

  flutter:
    sdk: flutter

  flutter_soloud:
    path: ../

  http: ^1.5.0
  logging: ^1.2.0

  web_socket_channel: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/audio/
    - assets/audio/12Bands/
