name: flutter_soloud_example
description: Demonstrates how to use the flutter_soloud plugin.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
homepage: https://github.com/alnitak/flutter_soloud
maintainer: Marco Bavagnoli (@lildeimos)

version: 0.1.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.8
  
  #https://pub.dev/packages/ffi
  ffi: ^2.1.2

  #https://pub.dev/packages/file_picker
  file_picker: ^8.1.2

  flutter:
    sdk: flutter

  flutter_soloud:
    path: ../

  #https://pub.dev/packages/logging
  logging: ^1.2.0

  #https://pub.dev/packages/path_provider
  path_provider: ^2.1.3

  #https://pub.dev/packages/permission_handler
  permission_handler: ^11.3.1

  #https://pub.dev/packages/star_menu
  star_menu: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/audio/
